# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/20140723/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.define "wire-testing_vm", primary: true do |s|

    s.vm.synced_folder "../../lib", "/mnt/project/lib"
    s.vm.synced_folder "../../bin", "/mnt/project/bin"
    s.vm.synced_folder "../../test", "/mnt/project/test"

    # install open vswitch parts ne weed
    s.vm.provision "shell", inline: <<EOS
echo == Ensure Open vSwitch is installed
      sudo apt-get install -yqq bridge-utils arping
      sudo apt-get install -yqq openvswitch-common openvswitch-switch openvswitch-test
echo == Install dnsmasq
      sudo apt-get install -yqq dnsmasq
EOS

    # install docker
    # https://docs.docker.com/installation/ubuntulinux/#ubuntu-trusty-1404-lts-64-bit
    s.vm.provision "shell", inline: <<EOS
echo == Ensure docker is installed
      [ -e /usr/lib/apt/methods/https ] || {
        sudo apt-get update -yqq
        sudo apt-get install -yqq apt-transport-https
      }
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
      sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
      sudo apt-get update -yqq
      sudo apt-get install -yqq lxc-docker

      #sudo docker pull ubuntu:14.04
EOS

    # install pip/fig
    s.vm.provision "shell", inline: <<EOS
echo == Ensure fig is installed
	PIP_=$(which pip)
	if [[ -z $PIP_ ]]; then
		sudo apt-get -yqq install python-pip
	fi 
	pip_ --version
	FIG_=$(which fig)
	if [[ -z $FIG_ ]]; then
		pip install fig
	fi
	fig --version
EOS

    # install gem needed by wire (by hand, not using bundler)
    # TODO remove when installing by wire gem
    s.vm.provision "shell", inline: <<EOS
echo == Ensure basic gems are installed, not yet via gem deps/bundler
	( gem list --local | grep -wq rainbow ) || sudo gem install rainbow --no-rdoc --no-ri
	( gem list --local | grep -wq thor ) || sudo gem install thor --no-rdoc --no-ri
EOS

    # install & run serverspec for the host
    s.vm.synced_folder "spec.d/", "/mnt/spec.d"

    s.vm.provision 'shell', inline: <<EOS
echo == Ensure serverspec is installed
( sudo gem list --local | grep -q serverspec ) || {
	sudo gem install rake -v '10.3.2' --no-rdoc --no-ri
	sudo gem install rspec -v '2.99.0' --no-rdoc --no-ri
	sudo gem install specinfra -v '1.21.0' --no-rdoc --no-ri
	sudo gem install serverspec -v '1.10.0' --no-rdoc --no-ri
}
EOS

    s.vm.provision 'shell', inline: <<EOS
echo == Ensure serverspec host test passes
cd /mnt/spec.d
rake spec
EOS

    # add link project dir in to vagrant home
    s.vm.provision 'shell', inline: <<EOS
    	[[ -L /home/vagrant/project ]] || ln -s /mnt/project /home/vagrant/project
EOS

    # run testcase.d test suite
    s.vm.provision 'shell', inline: <<EOS
echo == Running testcase
cd /mnt/project/test/ubuntu/testcase.d
rake spec
EOS

  end
  
end
